# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=schoolmanagersv;encrypt=true;trustServerCertificate=true
# spring.datasource.username=sa
# spring.datasource.password=123456
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://auto:14a1VRUGZrzaHVmA3oY4UoOfigqswtqu@dpg-d828mf50lvsc73c6ikrg-a.singapore-postgres.render.com/schoolmanager_pw46
spring.datasource.username=auto
spring.datasource.password=14a1VRUGZrzaHVmA3oY4UoOfigqswtqu

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true