spring.datasource.url=jdbc:sqlserver://den1.mssql7.gear.host:1433;databaseName=schoolmanager6;encrypt=true;trustServerCertificate=true
spring.datasource.username=schoolmanager6
spring.datasource.password=Tg8P~?l37mr9
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect